services:
  conservation-backend:
    environment:
      VCA_SHARED_STORAGE_CONTAINER_ROOT: /vca_v2/output/input
      VCA_ENGINE_OUTPUT_ROOT: /shared/vca/engine-output
    volumes:
      - ./shared:/shared
