server:
  port: 8080

spring:
  application:
    name: conservation_backend

conservation-guide-ai:
  base-url: ${CONSERVATION_GUIDE_AI_BASE_URL:http://localhost:8000}
pottery-inspection-ai:
  base-url: ${POTTERY_INSPECTION_AI_BASE_URL:http://localhost:8001}